[features]
seeds = false
skip-lint = false
[programs.localnet]
ajodao = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
# wallet = "/Users/personal/.config/solana/id.json"
wallet = "/home/david/.config/solana/id.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
